from django.urls import path

from .views import (
    JumpRuleDetailView,
    JumpRuleListCreateView,
    LoginView,
    NextQuestionView,
    PublicSurveyView,
    QuestionBankCrossStatsView,
    QuestionBankDetailView,
    QuestionBankListCreateView,
    QuestionBankNewVersionView,
    QuestionBankRemoveSharedView,
    QuestionBankRestoreView,
    QuestionBankShareView,
    QuestionBankSharedView,
    QuestionBankUpdateView,
    QuestionBankUsageView,
    QuestionBankVersionsView,
    QuestionDetailView,
    QuestionImportView,
    QuestionListCreateView,
    QuestionStatsView,
    RegisterView,
    SubmitSurveyView,
    SurveyCloseView,
    SurveyDetailView,
    SurveyDraftView,
    SurveyListCreateView,
    SurveyPublishView,
    SurveyStatsView,
)

urlpatterns = [
    path("auth/register", RegisterView.as_view()),
    path("auth/login", LoginView.as_view()),
    path("surveys", SurveyListCreateView.as_view()),
    path("surveys/<str:survey_id>", SurveyDetailView.as_view()),
    path("surveys/<str:survey_id>/publish", SurveyPublishView.as_view()),
    path("surveys/<str:survey_id>/close", SurveyCloseView.as_view()),
    path("surveys/<str:survey_id>/draft", SurveyDraftView.as_view()),
    path("surveys/<str:survey_id>/questions", QuestionListCreateView.as_view()),
    path("questions/<str:question_id>", QuestionDetailView.as_view()),
    path("surveys/<str:survey_id>/jump-rules", JumpRuleListCreateView.as_view()),
    path("jump-rules/<str:rule_id>", JumpRuleDetailView.as_view()),
    path("public/surveys/<str:slug>", PublicSurveyView.as_view()),
    path("public/surveys/<str:slug>/next-question", NextQuestionView.as_view()),
    path("public/surveys/<str:slug>/submit", SubmitSurveyView.as_view()),
    path("surveys/<str:survey_id>/stats", SurveyStatsView.as_view()),
    path("questions/<str:question_id>/stats", QuestionStatsView.as_view()),
    path("question-bank", QuestionBankListCreateView.as_view()),
    path("question-bank/shared", QuestionBankSharedView.as_view()),
    path("question-bank/<str:item_id>", QuestionBankDetailView.as_view()),
    path("question-bank/<str:item_id>/versions", QuestionBankVersionsView.as_view()),
    path("question-bank/<str:item_id>/new-version", QuestionBankNewVersionView.as_view()),
    path("question-bank/<str:item_id>/restore", QuestionBankRestoreView.as_view()),
    path("question-bank/<str:item_id>/share", QuestionBankShareView.as_view()),
    path("question-bank/<str:item_id>/usage", QuestionBankUsageView.as_view()),
    path("question-bank/<str:item_id>/update", QuestionBankUpdateView.as_view()),
    path("question-bank/<str:item_id>/cross-stats", QuestionBankCrossStatsView.as_view()),
    path("question-bank/<str:item_id>/remove-shared", QuestionBankRemoveSharedView.as_view()),
    path("surveys/<str:survey_id>/questions/import", QuestionImportView.as_view()),
]
